/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum DungeonsandtrollsDamageType {
    None = <any> 'none',
    Slash = <any> 'slash',
    Pierce = <any> 'pierce',
    Fire = <any> 'fire',
    Poison = <any> 'poison',
    Electric = <any> 'electric'
}
