/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DungeonsandtrollsAttributes } from './dungeonsandtrollsAttributes';
import { DungeonsandtrollsDroppable } from './dungeonsandtrollsDroppable';
import { DungeonsandtrollsEffect } from './dungeonsandtrollsEffect';
import { DungeonsandtrollsItem } from './dungeonsandtrollsItem';
import { DungeonsandtrollsSimpleItem } from './dungeonsandtrollsSimpleItem';
import { DungeonsandtrollsStun } from './dungeonsandtrollsStun';

export class DungeonsandtrollsMonster {
    'id'?: string;
    'name'?: string;
    'icon'?: string;
    'items'?: Array<DungeonsandtrollsSimpleItem>;
    'effects'?: Array<DungeonsandtrollsEffect>;
    'lifePercentage'?: number;
    'faction'?: string;
    'attributes'?: DungeonsandtrollsAttributes;
    'equippedItems'?: Array<DungeonsandtrollsItem>;
    'score'?: number | null;
    'algorithm'?: string | null;
    'onDeath'?: Array<DungeonsandtrollsDroppable>;
    'maxAttributes'?: DungeonsandtrollsAttributes;
    'lastDamageTaken'?: number | null;
    'stun'?: DungeonsandtrollsStun;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "icon",
            "baseName": "icon",
            "type": "string"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<DungeonsandtrollsSimpleItem>"
        },
        {
            "name": "effects",
            "baseName": "effects",
            "type": "Array<DungeonsandtrollsEffect>"
        },
        {
            "name": "lifePercentage",
            "baseName": "lifePercentage",
            "type": "number"
        },
        {
            "name": "faction",
            "baseName": "faction",
            "type": "string"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "DungeonsandtrollsAttributes"
        },
        {
            "name": "equippedItems",
            "baseName": "equippedItems",
            "type": "Array<DungeonsandtrollsItem>"
        },
        {
            "name": "score",
            "baseName": "score",
            "type": "number"
        },
        {
            "name": "algorithm",
            "baseName": "algorithm",
            "type": "string"
        },
        {
            "name": "onDeath",
            "baseName": "onDeath",
            "type": "Array<DungeonsandtrollsDroppable>"
        },
        {
            "name": "maxAttributes",
            "baseName": "maxAttributes",
            "type": "DungeonsandtrollsAttributes"
        },
        {
            "name": "lastDamageTaken",
            "baseName": "lastDamageTaken",
            "type": "number"
        },
        {
            "name": "stun",
            "baseName": "stun",
            "type": "DungeonsandtrollsStun"
        }    ];

    static getAttributeTypeMap() {
        return DungeonsandtrollsMonster.attributeTypeMap;
    }
}

