/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum DungeonsandtrollsItemType {
    Head = <any> 'head',
    MainHand = <any> 'mainHand',
    OffHand = <any> 'offHand',
    Body = <any> 'body',
    Legs = <any> 'legs',
    Neck = <any> 'neck'
}
