/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum DungeonsandtrollsEventType {
    Damage = <any> 'DAMAGE',
    Message = <any> 'MESSAGE',
    Buy = <any> 'BUY',
    Equip = <any> 'EQUIP',
    Error = <any> 'ERROR',
    Skill = <any> 'SKILL',
    Death = <any> 'DEATH',
    Score = <any> 'SCORE',
    Move = <any> 'MOVE',
    Aoe = <any> 'AOE'
}
