/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DungeonsandtrollsLevel } from './dungeonsandtrollsLevel';

export class DungeonsandtrollsMap {
    'levels'?: Array<DungeonsandtrollsLevel>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "levels",
            "baseName": "levels",
            "type": "Array<DungeonsandtrollsLevel>"
        }    ];

    static getAttributeTypeMap() {
        return DungeonsandtrollsMap.attributeTypeMap;
    }
}

