/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DungeonsandtrollsFogOfWarMap } from './dungeonsandtrollsFogOfWarMap';
import { DungeonsandtrollsMapObjects } from './dungeonsandtrollsMapObjects';
import { DungeonsandtrollsPlayerSpecificMap } from './dungeonsandtrollsPlayerSpecificMap';

export class DungeonsandtrollsLevel {
    'level'?: number;
    'width'?: number;
    'height'?: number;
    'horror'?: number;
    'deprecationInSeconds'?: number;
    'objects'?: Array<DungeonsandtrollsMapObjects>;
    'fogOfWar'?: Array<DungeonsandtrollsFogOfWarMap>;
    'playerMap'?: Array<DungeonsandtrollsPlayerSpecificMap>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "level",
            "baseName": "level",
            "type": "number"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "horror",
            "baseName": "horror",
            "type": "number"
        },
        {
            "name": "deprecationInSeconds",
            "baseName": "deprecationInSeconds",
            "type": "number"
        },
        {
            "name": "objects",
            "baseName": "objects",
            "type": "Array<DungeonsandtrollsMapObjects>"
        },
        {
            "name": "fogOfWar",
            "baseName": "fogOfWar",
            "type": "Array<DungeonsandtrollsFogOfWarMap>"
        },
        {
            "name": "playerMap",
            "baseName": "playerMap",
            "type": "Array<DungeonsandtrollsPlayerSpecificMap>"
        }    ];

    static getAttributeTypeMap() {
        return DungeonsandtrollsLevel.attributeTypeMap;
    }
}

