/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DungeonsandtrollsAttributes } from './dungeonsandtrollsAttributes';

export class DungeonsandtrollsSkillAttributes {
    'strength'?: DungeonsandtrollsAttributes;
    'dexterity'?: DungeonsandtrollsAttributes;
    'intelligence'?: DungeonsandtrollsAttributes;
    'willpower'?: DungeonsandtrollsAttributes;
    'constitution'?: DungeonsandtrollsAttributes;
    'slashResist'?: DungeonsandtrollsAttributes;
    'pierceResist'?: DungeonsandtrollsAttributes;
    'fireResist'?: DungeonsandtrollsAttributes;
    'poisonResist'?: DungeonsandtrollsAttributes;
    'electricResist'?: DungeonsandtrollsAttributes;
    'life'?: DungeonsandtrollsAttributes;
    'stamina'?: DungeonsandtrollsAttributes;
    'mana'?: DungeonsandtrollsAttributes;
    'constant'?: DungeonsandtrollsAttributes;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "strength",
            "baseName": "strength",
            "type": "DungeonsandtrollsAttributes"
        },
        {
            "name": "dexterity",
            "baseName": "dexterity",
            "type": "DungeonsandtrollsAttributes"
        },
        {
            "name": "intelligence",
            "baseName": "intelligence",
            "type": "DungeonsandtrollsAttributes"
        },
        {
            "name": "willpower",
            "baseName": "willpower",
            "type": "DungeonsandtrollsAttributes"
        },
        {
            "name": "constitution",
            "baseName": "constitution",
            "type": "DungeonsandtrollsAttributes"
        },
        {
            "name": "slashResist",
            "baseName": "slashResist",
            "type": "DungeonsandtrollsAttributes"
        },
        {
            "name": "pierceResist",
            "baseName": "pierceResist",
            "type": "DungeonsandtrollsAttributes"
        },
        {
            "name": "fireResist",
            "baseName": "fireResist",
            "type": "DungeonsandtrollsAttributes"
        },
        {
            "name": "poisonResist",
            "baseName": "poisonResist",
            "type": "DungeonsandtrollsAttributes"
        },
        {
            "name": "electricResist",
            "baseName": "electricResist",
            "type": "DungeonsandtrollsAttributes"
        },
        {
            "name": "life",
            "baseName": "life",
            "type": "DungeonsandtrollsAttributes"
        },
        {
            "name": "stamina",
            "baseName": "stamina",
            "type": "DungeonsandtrollsAttributes"
        },
        {
            "name": "mana",
            "baseName": "mana",
            "type": "DungeonsandtrollsAttributes"
        },
        {
            "name": "constant",
            "baseName": "constant",
            "type": "DungeonsandtrollsAttributes"
        }    ];

    static getAttributeTypeMap() {
        return DungeonsandtrollsSkillAttributes.attributeTypeMap;
    }
}

