/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DungeonsandtrollsItemType } from './dungeonsandtrollsItemType';

export class DungeonsandtrollsSimpleItem {
    'name'?: string;
    'slot'?: DungeonsandtrollsItemType;
    'icon'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "slot",
            "baseName": "slot",
            "type": "DungeonsandtrollsItemType"
        },
        {
            "name": "icon",
            "baseName": "icon",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DungeonsandtrollsSimpleItem.attributeTypeMap;
    }
}

export namespace DungeonsandtrollsSimpleItem {
}
