/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DungeonsandtrollsCharacter } from './dungeonsandtrollsCharacter';
import { DungeonsandtrollsDecoration } from './dungeonsandtrollsDecoration';
import { DungeonsandtrollsEffect } from './dungeonsandtrollsEffect';
import { DungeonsandtrollsItem } from './dungeonsandtrollsItem';
import { DungeonsandtrollsMonster } from './dungeonsandtrollsMonster';
import { DungeonsandtrollsPosition } from './dungeonsandtrollsPosition';
import { DungeonsandtrollsWaypoint } from './dungeonsandtrollsWaypoint';

export class DungeonsandtrollsMapObjects {
    'position'?: DungeonsandtrollsPosition;
    'monsters'?: Array<DungeonsandtrollsMonster>;
    'players'?: Array<DungeonsandtrollsCharacter>;
    'isStairs'?: boolean;
    'portal'?: DungeonsandtrollsWaypoint;
    'decorations'?: Array<DungeonsandtrollsDecoration>;
    'effects'?: Array<DungeonsandtrollsEffect>;
    'items'?: Array<DungeonsandtrollsItem>;
    'isFree'?: boolean;
    'isWall'?: boolean;
    'isDoor'?: boolean;
    'isSpawn'?: boolean | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "position",
            "baseName": "position",
            "type": "DungeonsandtrollsPosition"
        },
        {
            "name": "monsters",
            "baseName": "monsters",
            "type": "Array<DungeonsandtrollsMonster>"
        },
        {
            "name": "players",
            "baseName": "players",
            "type": "Array<DungeonsandtrollsCharacter>"
        },
        {
            "name": "isStairs",
            "baseName": "isStairs",
            "type": "boolean"
        },
        {
            "name": "portal",
            "baseName": "portal",
            "type": "DungeonsandtrollsWaypoint"
        },
        {
            "name": "decorations",
            "baseName": "decorations",
            "type": "Array<DungeonsandtrollsDecoration>"
        },
        {
            "name": "effects",
            "baseName": "effects",
            "type": "Array<DungeonsandtrollsEffect>"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<DungeonsandtrollsItem>"
        },
        {
            "name": "isFree",
            "baseName": "isFree",
            "type": "boolean"
        },
        {
            "name": "isWall",
            "baseName": "isWall",
            "type": "boolean"
        },
        {
            "name": "isDoor",
            "baseName": "isDoor",
            "type": "boolean"
        },
        {
            "name": "isSpawn",
            "baseName": "isSpawn",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return DungeonsandtrollsMapObjects.attributeTypeMap;
    }
}

