/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DungeonsandtrollsDroppable } from './dungeonsandtrollsDroppable';
import { DungeonsandtrollsSkillAttributes } from './dungeonsandtrollsSkillAttributes';
import { DungeonsandtrollsSkillSpecificFlags } from './dungeonsandtrollsSkillSpecificFlags';

export class DungeonsandtrollsSkillEffect {
    'attributes'?: DungeonsandtrollsSkillAttributes;
    'flags'?: DungeonsandtrollsSkillSpecificFlags;
    'summons'?: Array<DungeonsandtrollsDroppable>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "DungeonsandtrollsSkillAttributes"
        },
        {
            "name": "flags",
            "baseName": "flags",
            "type": "DungeonsandtrollsSkillSpecificFlags"
        },
        {
            "name": "summons",
            "baseName": "summons",
            "type": "Array<DungeonsandtrollsDroppable>"
        }    ];

    static getAttributeTypeMap() {
        return DungeonsandtrollsSkillEffect.attributeTypeMap;
    }
}

