/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DungeonsandtrollsPosition } from './dungeonsandtrollsPosition';

export class DungeonsandtrollsKey {
    'doors'?: Array<DungeonsandtrollsPosition>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "doors",
            "baseName": "doors",
            "type": "Array<DungeonsandtrollsPosition>"
        }    ];

    static getAttributeTypeMap() {
        return DungeonsandtrollsKey.attributeTypeMap;
    }
}

