/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DungeonsandtrollsAttributes } from './dungeonsandtrollsAttributes';
import { DungeonsandtrollsItemType } from './dungeonsandtrollsItemType';
import { DungeonsandtrollsSkill } from './dungeonsandtrollsSkill';

export class DungeonsandtrollsItem {
    'id'?: string;
    'name'?: string;
    'slot'?: DungeonsandtrollsItemType;
    'price'?: number;
    'requirements'?: DungeonsandtrollsAttributes;
    'attributes'?: DungeonsandtrollsAttributes;
    'skills'?: Array<DungeonsandtrollsSkill>;
    'icon'?: string;
    'unidentified'?: boolean | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "slot",
            "baseName": "slot",
            "type": "DungeonsandtrollsItemType"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        },
        {
            "name": "requirements",
            "baseName": "requirements",
            "type": "DungeonsandtrollsAttributes"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "DungeonsandtrollsAttributes"
        },
        {
            "name": "skills",
            "baseName": "skills",
            "type": "Array<DungeonsandtrollsSkill>"
        },
        {
            "name": "icon",
            "baseName": "icon",
            "type": "string"
        },
        {
            "name": "unidentified",
            "baseName": "unidentified",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return DungeonsandtrollsItem.attributeTypeMap;
    }
}

export namespace DungeonsandtrollsItem {
}
