/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DungeonsandtrollsSkillSpecificFlags {
    'movement'?: boolean;
    'knockback'?: boolean;
    'stun'?: boolean;
    'groundEffect'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "movement",
            "baseName": "movement",
            "type": "boolean"
        },
        {
            "name": "knockback",
            "baseName": "knockback",
            "type": "boolean"
        },
        {
            "name": "stun",
            "baseName": "stun",
            "type": "boolean"
        },
        {
            "name": "groundEffect",
            "baseName": "groundEffect",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return DungeonsandtrollsSkillSpecificFlags.attributeTypeMap;
    }
}

